name: mos_teacher
description: A new flutter app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: res/fonts/Lato-Regular.ttf
          weight: 400
        - asset: res/fonts/Lato-Medium.ttf
          weight: 500
        - asset: res/fonts/Lato-Bold.ttf
          weight: 700
