name: mos_teacher
description: A new flutter app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  flutter:
    sdk: flutter
  # state
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  # ui
  flutter_svg: ^0.23.0+1
  # services
  url_launcher: ^6.0.17

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  # linter
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - res/image/png/
    - res/image/svg/
  fonts:
    - family: Lato
      fonts:
        - asset: res/fonts/Lato-Regular.ttf
          weight: 400
        - asset: res/fonts/Lato-Medium.ttf
          weight: 500
        - asset: res/fonts/Lato-Bold.ttf
          weight: 700
